# Generated by Django 3.0.2 on 2020-09-17 15:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bloodpressure',
            options={'managed': True, 'ordering': ['-created'], 'verbose_name': 'BloodPressure', 'verbose_name_plural': 'BloodPressures'},
        ),
        migrations.AlterModelOptions(
            name='note',
            options={'managed': True, 'ordering': ['-created'], 'verbose_name': 'Note', 'verbose_name_plural': 'Notes'},
        ),
        migrations.AlterModelOptions(
            name='temperature',
            options={'managed': True, 'ordering': ['-created'], 'verbose_name': 'Temperature', 'verbose_name_plural': 'Temperatures'},
        ),
        migrations.AlterModelOptions(
            name='testresult',
            options={'managed': True, 'ordering': ['-created'], 'verbose_name': 'TestResult', 'verbose_name_plural': 'TestResults'},
        ),
        migrations.AlterModelOptions(
            name='weight',
            options={'managed': True, 'ordering': ['-created'], 'verbose_name': 'Weight', 'verbose_name_plural': 'Weights'},
        ),
        migrations.AddField(
            model_name='bloodpressure',
            name='created',
            field=models.DateTimeField(auto_now=True, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='medication',
            name='receiver',
            field=models.ForeignKey(default=32, on_delete=django.db.models.deletion.CASCADE, related_name='medicationreceiver', to=settings.AUTH_USER_MODEL, verbose_name='receiver'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medication',
            name='sender',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, related_name='medicationsender', to='backend.Doctor', verbose_name='sender'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='note',
            name='created',
            field=models.DateTimeField(auto_now=True, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='note',
            name='receiver',
            field=models.ForeignKey(default=32, on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to=settings.AUTH_USER_MODEL, verbose_name='receiver'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='temperature',
            name='created',
            field=models.DateTimeField(auto_now=True, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='testresult',
            name='created',
            field=models.DateTimeField(auto_now=True, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='user',
            name='licenseNumber',
            field=models.CharField(default='null', max_length=150, verbose_name='License number'),
        ),
        migrations.AddField(
            model_name='weight',
            name='created',
            field=models.DateTimeField(auto_now=True, verbose_name='created'),
        ),
        migrations.RemoveField(
            model_name='note',
            name='sender',
        ),
        migrations.AddField(
            model_name='note',
            name='sender',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='backend.Doctor', verbose_name='sender'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patient',
            name='aproved',
            field=models.ManyToManyField(related_name='aproved', to='backend.Doctor', verbose_name='aproved'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='medication',
            field=models.ManyToManyField(related_name='medication', to='backend.Medication', verbose_name='medication'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient', to=settings.AUTH_USER_MODEL, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='routine',
            name='end',
            field=models.DateTimeField(verbose_name='end'),
        ),
        migrations.AlterField(
            model_name='routine',
            name='start',
            field=models.DateTimeField(verbose_name='start'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_MP',
            field=models.BooleanField(),
        ),
    ]
