# Generated by Django 3.0.2 on 2020-09-04 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_user_licensenumber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_MP',
            new_name='isMP',
        ),
    ]
