# Generated by Django 3.0.2 on 2020-09-04 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20200904_1724'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='isMP',
            new_name='is_MP',
        ),
    ]
