# Generated by Django 3.0.2 on 2020-09-16 21:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20200904_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='receiver',
            field=models.ManyToManyField(related_name='receiver', to=settings.AUTH_USER_MODEL, verbose_name='receiver'),
        ),
        migrations.AlterField(
            model_name='note',
            name='sender',
            field=models.ManyToManyField(related_name='sender', to='backend.Doctor', verbose_name='sender'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='aproved',
            field=models.ManyToManyField(related_name='aproved', to='backend.Doctor', verbose_name='aproved'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='medication',
            field=models.ManyToManyField(to='backend.Medication', verbose_name='medication'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient', to=settings.AUTH_USER_MODEL, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_MP',
            field=models.BooleanField(),
        ),
    ]
