# Generated by Django 3.0.2 on 2020-09-16 21:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20200916_2200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='receiver',
        ),
        migrations.AddField(
            model_name='note',
            name='receiver',
            field=models.ForeignKey(default=32, on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to=settings.AUTH_USER_MODEL, verbose_name='receiver'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='note',
            name='sender',
        ),
        migrations.AddField(
            model_name='note',
            name='sender',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='backend.Doctor', verbose_name='sender'),
            preserve_default=False,
        ),
    ]
