# Generated by Django 3.0.2 on 2020-09-17 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_auto_20200916_2324'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bloodpressure',
            options={'managed': True, 'ordering': ['-created'], 'verbose_name': 'BloodPressure', 'verbose_name_plural': 'BloodPressures'},
        ),
        migrations.AlterModelOptions(
            name='note',
            options={'managed': True, 'ordering': ['-created'], 'verbose_name': 'Note', 'verbose_name_plural': 'Notes'},
        ),
        migrations.AlterModelOptions(
            name='temperature',
            options={'managed': True, 'ordering': ['-created'], 'verbose_name': 'Temperature', 'verbose_name_plural': 'Temperatures'},
        ),
        migrations.AlterModelOptions(
            name='testresult',
            options={'managed': True, 'ordering': ['-created'], 'verbose_name': 'TestResult', 'verbose_name_plural': 'TestResults'},
        ),
        migrations.AlterModelOptions(
            name='weight',
            options={'managed': True, 'ordering': ['-created'], 'verbose_name': 'Weight', 'verbose_name_plural': 'Weights'},
        ),
        migrations.AddField(
            model_name='bloodpressure',
            name='created',
            field=models.TimeField(auto_now=True, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='note',
            name='created',
            field=models.TimeField(auto_now=True, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='temperature',
            name='created',
            field=models.TimeField(auto_now=True, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='testresult',
            name='created',
            field=models.TimeField(auto_now=True, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='weight',
            name='created',
            field=models.TimeField(auto_now=True, verbose_name='created'),
        ),
    ]
