# Generated by Django 3.0.2 on 2020-09-17 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_auto_20200917_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodpressure',
            name='created',
            field=models.DateTimeField(auto_now=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='note',
            name='created',
            field=models.DateTimeField(auto_now=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='routine',
            name='end',
            field=models.DateTimeField(verbose_name='end'),
        ),
        migrations.AlterField(
            model_name='routine',
            name='start',
            field=models.DateTimeField(verbose_name='start'),
        ),
        migrations.AlterField(
            model_name='temperature',
            name='created',
            field=models.DateTimeField(auto_now=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='created',
            field=models.DateTimeField(auto_now=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='weight',
            name='created',
            field=models.DateTimeField(auto_now=True, verbose_name='created'),
        ),
    ]
